"use client"
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import Link from 'next/link'

/////////
/////////
///////// Header Code from TailwindUI - START /////////
/////////
/////////

import { Fragment, useState } from 'react'
import { Dialog } from '@headlessui/react'
import {
  ArrowPathIcon,
  Bars3Icon,
  ChartPieIcon,
  CursorArrowRaysIcon,
  FingerPrintIcon,
  SquaresPlusIcon,
  XMarkIcon,
} from '@heroicons/react/24/outline'

// function classNames(...classes) {
//   return classes.filter(Boolean).join(' ')
// }

/////////
/////////
///////// Header Code from TailwindUI - END /////////
/////////
/////////

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'ourStory: Internal Design Engineer Portal',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)

  const header = (
    <header className="bg-white">
      <nav className="mx-auto flex max-w-7xl items-center justify-between p-6 lg:px-8" aria-label="Global">
        <div className="flex lg:flex-1">
          <a href="/" className="-m-1.5 p-1.5">
            <span className="sr-only">Your Company</span>
            <img className="h-8 w-auto" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="" />
          </a>
        </div>
        <div className="flex lg:hidden">
          <button
            type="button"
            className="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700"
            onClick={() => setMobileMenuOpen(true)}
          >
            <span className="sr-only">Open main menu</span>
            <Bars3Icon className="h-6 w-6" aria-hidden="true" />
          </button>
        </div>
        <div className="hidden lg:flex lg:gap-x-12">
          <a href="/manifesto" className="text-sm font-semibold leading-6 text-gray-900">
            Manifesto
          </a>
          <a href="/protocol" className="text-sm font-semibold leading-6 text-gray-900">
            Protocol
          </a>
          <a href="/platforms" className="text-sm font-semibold leading-6 text-gray-900">
            Platforms
          </a>
        </div>
        <div className="hidden lg:flex lg:flex-1 lg:justify-end">
          <a href="https://github.com/ourStoryNetwork" target="_blank" rel="noopener noreferrer" className="text-sm font-semibold leading-6 text-gray-900">
            GitHub <span aria-hidden="true">&rarr;</span>
          </a>
        </div>
      </nav>
      <Dialog as="div" className="lg:hidden" open={mobileMenuOpen} onClose={setMobileMenuOpen}>
        <div className="fixed inset-0 z-10" />
        <Dialog.Panel className="fixed inset-y-0 right-0 z-10 w-full overflow-y-auto bg-white px-6 py-6 sm:max-w-sm sm:ring-1 sm:ring-gray-900/10">
          <div className="flex items-center justify-between">
            <a href="/" className="-m-1.5 p-1.5">
              <span className="sr-only">Your Company</span>
              <img
                className="h-8 w-auto"
                src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600"
                alt=""
              />
            </a>
            <button
              type="button"
              className="-m-2.5 rounded-md p-2.5 text-gray-700"
              onClick={() => setMobileMenuOpen(false)}
            >
              <span className="sr-only">Close menu</span>
              <XMarkIcon className="h-6 w-6" aria-hidden="true" />
            </button>
          </div>
          <div className="mt-6 flow-root">
            <div className="-my-6 divide-y divide-gray-500/10">
              <div className="space-y-2 py-6">
                <a href="/manifesto" className="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">
                  Manifesto
                </a>
                <a href="/protocl" className="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">
                  Protocol
                </a>
                <a href="/platforms" className="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">
                  Platforms
                </a>
              </div>
              <div className="py-6">
                <a href="https://github.com/ourStoryNetwork" target="_blank" rel="noopener noreferrer" className="-mx-3 block rounded-lg px-3 py-2.5 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">
                  GitHub
                </a>
              </div>
            </div>
          </div>
        </Dialog.Panel>
      </Dialog>
    </header> 
  );

  const footer = (
    <footer>
      <div className='border-t border-slate-400 mt-12 py-6 text-center text-slate-400'>
        <p>Design Engineered for oS3 by ourStory | hu3agency | trainfarb</p>
      </div>
    </footer> 
  );

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mx-auto max-w-6xl px-6">
          {header}
          {children}
          {footer}
        </div>
      </body>
    </html>
  );
}
